#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Mar 16 15:07:05 2021

@author: noe
"""
import pandas as pd
pd.set_option('display.max_columns', None)

data = pd.read_csv("/Users/noe/Desktop/CNAM/Carto/Projet géo/Grenoble Politique/Grenoble_eligibilité.csv")
newData = pd.DataFrame(columns = ["dpt", "techno_maj", "débit_maj", "pourcentage_bas_debit"])

for i in data["imb_longitude"].unique() :
    
    currentBuilding = data[data["imb_longitude"] == i]
    mainTech     = currentBuilding['code_techno'].value_counts().idxmax()
    mainDeb      = currentBuilding['classe_debit_descendant'].value_counts().idxmax()
    debits       = currentBuilding['classe_debit_descendant'].value_counts()
    nb_bas_debit = 0
    
    if "INEL" in debits.index :
        nb_bas_debit += debits["INEL"]
    
    if "HD05" in debits.index :
        nb_bas_debit += debits["HD05"]
    
    nb_lignes = currentBuilding.shape[0]
    
    pourcentage = nb_bas_debit/nb_lignes*100

    newRow = {"imb_longitude" : currentBuilding["imb_longitude"].unique()[0] ,"imb_latitude" : currentBuilding["imb_latitude"].unique()[0], "techno_maj" : mainTech, "débit_maj" : mainDeb, "pourcentage_bas_debit" : int(round(pourcentage))}
    
    newData = newData.append(newRow, ignore_index=True)

newData.to_csv("/Users/noe/Desktop/CNAM/Carto/Projet géo/Grenoble tech-débit majoritaire.csv", sep = ";")